### ISSUE TITLE
UAM 

### ISSUE THREAD

**Issue by Heiner1** [MarkMpn/AutotuneWeb#13]
I tested and found that I get exactly the same result either with or without UAM categorized as basal. Could this be the truth? I'm announcing all of my meals (I hope) but the same result down to the 3rd decimal place? 
But thank you and Dana  for this great work; all of this will result in more and more acceptance at our doctors.

**Comment by MarkMpn** [comment]
Can you let me know your NS URL or email and I'll check that the jobs were run as expected with the different UAM options? If they were, you might be better off asking in the autotune gitter channel as they know a lot more about the internals of how Autotune produces its suggestions than I do.

**Comment by Heiner1** [comment]
https://wkns.herokuapp.com  at the moment it's open, so you can debug or s.th. else. THX

**Comment by MarkMpn** [comment]
Looks like this is due to this change in Autotune: https://github.com/openaps/oref0/commit/fd53d840e68ef76d7b34684f5546480b6505271d

This essentially sets the "Categorize UAM as Basal" option if it detects at least 1 hour of carb absorption, on the assumption that you have input all the carbs you've eaten and therefore any other deviations must be due to basal rather than unannounced meals.
