### ISSUE TITLE
Temporary basal records in this Nightscout instance do not include a "rate" property - they will not be taken into account by Autotune

### ISSUE THREAD

**Issue by vonstein2002** [MarkMpn/AutotuneWeb#4]
I am using NSClient2 2.0 Build 4f0f947ed-2018.11.03-00:28 and NightScout  0.10.3-master-20180805  I am still getting the message about temp basal entries in NightScout not having the "rate" property.  have aslo tried AndroidAPS 2.0 master and had the same problem.  Any ideas?

**Comment by MarkMpn** [comment]
This message is generated if either:

1. You don't have any temp basal entries in Nightscout, or
2. The latest 10 temp basal entries don't have the `rate` property specified

If you do have temp basal entries in Nightscout, then they would seem to be missing the `rate` property that is required by Autotune. The only reason I can see that AAPS would upload a temp basal record to Nightscout without this property is if you are using percentage-based temp basal rates rather than absolute temp basal rates, and you don't have a profile selected in AAPS.
